parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint/eslint-plugin"
extends:
  - '@react-native-community'
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
root: true
rules:
  # note you must disable the base rule as it can report incorrect errors
  no-shadow: off
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-explicit-any': off
  # no relative imports
  no-restricted-imports:
    - error
    - patterns:
      - ".*"
