name: Bug report
description: Report an issue with Reorderable List.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue you are facing. Include what you expect to happen, what actually happens and a video of the issue if possible.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide the steps necessary to reproduce the bug.
      placeholder: |
        1. Scroll the list until item at index 4
        2. Long press on item at index 4
        3. Drag the item to index 7 and release it
    validations:
      required: true

  - type: textarea
    id: minimal-reproducible-example
    attributes:
      label: Minimal reproducible example
      description: Please provide a minimal working example to reproduce the bug. It can be a link to a repository, a link to a snack (https://snack.expo.dev) or the actual code. Please make sure it contains the minimum necessary to reproduce the bug as described here https://stackoverflow.com/help/minimal-reproducible-example.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please provide any relevant logs encountered when this bug occurs.

  - type: input
    id: reorderable-list-version
    attributes:
      label: Reorderable List version
      placeholder: 0.7.0
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      placeholder: 0.76.5
    validations:
      required: true

  - type: dropdown
    id: project-type
    attributes:
      label: Project type
      options:
        - Bare React Native
        - Expo
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - Paper (Old Architecture)
        - Fabric (New Architecture)
    validations:
      required: true

  - type: input
    id: reanimated-version
    attributes:
      label: Reanimated version
      placeholder: 3.16.6
    validations:
      required: true

  - type: input
    id: gesture-handler-version
    attributes:
      label: Gesture Handler version
      placeholder: 2.21.2
    validations:
      required: true

  - type: dropdown
    id: affected-platforms
    attributes:
      label: Affected platforms
      multiple: true
      options:
        - iOS
        - Android
    validations:
      required: true

